homepage:
    pattern:  /
    defaults: { _controller: DellaertWebappDeploymentBundle:Main:index }

Dashboard:
    pattern:  /dashboard
    defaults: { _controller: DellaertWebappDeploymentBundle:Main:index }

Help:
    pattern: /help
    defaults: { _controller: DellaertWebappDeploymentBundle:Main:help }

Server:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-server.yml"
    prefix:   /server

DeploymentType:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-deploymenttype.yml"
    prefix:   /deployment-type

APIKey:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-apikey.yml"
    prefix:   /api-key

Application:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-application.yml"
    prefix:   /application

ApplicationParameterValue:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-applicationparametervalue.yml"
    prefix:   /application-parameter-value

ApplicationTemplate:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-applicationtemplate.yml"
    prefix:   /application-template

ApplicationTemplateParameter:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-applicationtemplateparameter.yml"
    prefix:   /application-template-parameter

DatabaseType:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-databasetype.yml"
    prefix:   /database-type

Deployment:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-deployment.yml"
    prefix:   /deployment