ServerTypeList:
    pattern: /
    defaults: { _controller: DellaertWebappDeploymentBundle:ServerType:list}

ServerTypeListData:
    pattern: /listdata
    defaults: { _controller: DellaertWebappDeploymentBundle:ServerType:listData}

ServerTypeAdd:
    pattern: /add
    defaults: { _controller: DellaertWebappDeploymentBundle:ServerType:add}

ServerTypeEdit:
    pattern: /edit/{id}
    defaults: { _controller: DellaertWebappDeploymentBundle:ServerType:edit}
    requirements:
        id: \d+

ServerTypeDelete:
    pattern: /delete/{id}
    defaults: { _controller: DellaertWebappDeploymentBundle:ServerType:delete}
    requirements:
        id: \d+

ServerTypeViewSlug:
    pattern: /{slug}
    defaults: { _controller: DellaertWebappDeploymentBundle:ServerType:view}