homepage:
    pattern:  /
    defaults: { _controller: DellaertWebappDeploymentBundle:Main:index }

Dashboard:
    pattern:  /dashboard
    defaults: { _controller: DellaertWebappDeploymentBundle:Main:index }

Help:
    pattern: /help
    defaults: { _controller: DellaertWebappDeploymentBundle:Main:help }

Server:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-server.yml"
    prefix:   /server

ServerType:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-servertype.yml"
    prefix:   /server-type

APIKey:
    resource: "@DellaertWebappDeploymentBundle/Resources/config/routing-apikey.yml"
    prefix:   /api-key