parameters:
#    dellaert_webapp_deployment.example.class: Dellaert\WebappDeploymentBundle\Example

services:
#    dellaert_webapp_deployment.example:
#        class: %dellaert_webapp_deployment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
